# Generated by Django 5.2.4 on 2025-07-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(db_index=True, max_length=100)),
                ('inspection_by', models.CharField(max_length=100)),
                ('inspection_date', models.DateField()),
                ('bogie_details', models.JSONField()),
                ('bogie_checksheet', models.JSONField()),
                ('bmbc_checksheet', models.JSONField()),
                ('status', models.CharField(default='Saved', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WheelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(db_index=True, max_length=100)),
                ('submitted_by', models.CharField(max_length=100)),
                ('submitted_date', models.DateField()),
                ('fields', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
